name: .conda_flexiai
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - expat=2.7.0
  - giflib=5.2.2
  - lcms2=2.17
  - ld_impl_linux-64=2.40
  - leptonica=1.83.1
  - lerc=4.0.0
  - libarchive=3.7.7
  - libdeflate=1.24
  - libexpat=2.7.0
  - libffi=3.4.4
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmpdec=4.0.0
  - libpng=1.6.47
  - libsqlite=3.49.2
  - libstdcxx=15.1.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - lzo=2.10
  - ncurses=6.5
  - openjpeg=2.5.3
  - openssl=3.5.0
  - packaging=25.0
  - pillow=11.2.1
  - pip=25.1
  - pthread-stubs=0.4
  - pytesseract=0.3.13
  - python=3.12
  - python_abi=3.12
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.49.2
  - tesseract=5.5.0
  - tk=8.6.13
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.9.0
      - attrs==25.3.0
      - azure-ai-inference==1.0.0b9
      - azure-core==1.34.0
      - blinker==1.9.0
      - build==1.2.2.post1
      - cachetools==5.5.2
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.2.0
      - distro==1.9.0
      - dotenv==0.9.9
      - et-xmlfile==2.0.0
      - flask==3.1.1
      - frozenlist==1.6.0
      - google-api-core==2.24.2
      - google-api-python-client==2.169.0
      - google-auth==2.40.1
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.2.2
      - googleapis-common-protos==1.70.0
      - greenlet==3.2.2
      - h11==0.16.0
      - h2==4.2.0
      - hpack==4.1.0
      - httpcore==1.0.9
      - httplib2==0.22.0
      - httpx==0.28.1
      - hypercorn==0.17.3
      - hyperframe==6.1.0
      - idna==3.10
      - isodate==0.7.2
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jiter==0.9.0
      - markupsafe==3.0.2
      - multidict==6.4.3
      - numpy==2.2.5
      - oauthlib==3.2.2
      - openai==1.79.0
      - opencv-python==4.11.0.86
      - openpyxl==3.1.5
      - pandas==2.2.3
      - pip-tools==7.4.1
      - priority==2.0.0
      - propcache==0.3.1
      - proto-plus==1.26.1
      - protobuf==6.31.0
      - psutil==7.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pydantic-settings==2.9.1
      - pyparsing==3.2.3
      - pyproject-hooks==1.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - pytz==2025.2
      - quart==0.20.0
      - redis==6.1.0
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - six==1.17.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.41
      - tiktoken==0.9.0
      - tqdm==4.67.1
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - uritemplate==4.1.1
      - urllib3==2.4.0
      - werkzeug==3.1.3
      - wsproto==1.2.0
      - yarl==1.20.0

